version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgre_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  task3:
    build: .
    restart: always
    ports:
      - 3000:3000

volumes:
  postgre_volume:
